### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by amchos**

### CODE REVIEW

**Comment by valerimirzoyan** [comment]
the code doesn't work and it would be better if it was all in html

**Comment by amchos** [comment]
> the code doesn't work and it would be better if it was all in html
Hi. I think you did something wrong. Did you make a git clone of my repository or just download files manually?
And no, its a bad practice to write all your JS and CSS code in the same file with HTML. You can do it and it will work but it's better not to do it) It only feels handy on small projects.

**Comment by valerimirzoyan** [comment]
> 

I download files manually

**Comment by valerimirzoyan** [comment]
> > the code doesn't work and it would be better if it was all in html
> > Hi. I think you did something wrong. Did you make a git clone of my repository or just download files manually?
> > And no, its a bad practice to write all your JS and CSS code in the same file with HTML. You can do it and it will work but it's better not to do it) It only feels handy on small projects.

Yes I know that but it would be faster for the reader ;)

**Comment by amchos** [comment]
> > 
> 
> I download files manually

Try to do git clone or correctly change path in JS and CSS links inside HTML file after downloading files manually. Actually i can show you how to do git clone if you are in tumolabs now

**Comment by AroLalayan** [comment]
Change BG color button-ի ֆունկցիոնալը աշխատում է,
դիզայնը իմ դուրը գալիս է մենակ խորհուրդ կտայի input-ի փոխարեն, textarea-ով փոխարինեիք
առաջադրանքի բոլոր կետերը կատարված են, ֆունկցիոնալը հիանալի աշխատում է
պրոյեկտը համարում եմ հաջողված ( Success )

**Pull request merged**
